name = "infoshell-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "infoshell-db"
database_id = "11b1aaa4-30e5-4190-aae4-3e67dbdc3325"

[[r2_buckets]]
binding = "BANNERS"
bucket_name = "infoshell-banners"

[vars]
CORS_ORIGIN = "*"
